### ISSUE TITLE
Understanding performance and scaling results of a new photon emitter class

### ISSUE THREAD

**Issue by andrewgait** [mitsuba-renderer/mitsuba3#1465]
I've recently joined a project at the University of Manchester in the UK where we are trying to use the rendering capabilities of Mitsuba3 as a substitute for the current (slow) rendering methods in the CERN codebase Geant4.  

To this end, we have created our own fork of the main Mitsuba3 repository and written a new photon emitter (loosely based on the spot emitter, but adapted to allow us to read in information for multiple photons in a single emitter).  As I understand it, an attempt was made to use a single emitter for each photon, but this was abandoned due to the JIT compilation time becoming too large for >10^6 photons.

The code for the fork can be seen at https://github.com/UoMResearchIT/mitsuba3-manchester, with the additions being in src/emitters/photon.cpp; we have also added src/integrators/custom_ptracer.cpp but I think (this work was done before I joined the project, so I'm only going off the code I've received) that this was only in order to do some performance / scaling measurements of the ray sampling, and some scripts we have been using to test performance and scaling on both CPU and GPU are in the MPhys/Single_Emitter directory in that repo.

We are trying to understand the performance and scaling results that we are seeing for our emitter - in a nutshell, it appears that the `render()` step in Mitsuba3 of examples we have tried so far does not scale with the number of photons - no matter how many photons we load in to the emitter, the `render()` step takes roughly the same amount of time (this is documented in the MPhys/Single_Emitter/performance_scaling_experiments directory).  The results we get back in terms of the rendered images we see for the experiments we have run look sensible, so we are not sure whether we have done something "wrong" in terms of our new emitter, or whether Mitsuba3 / DrJit is doing something "clever" in terms of the photon ray paths that have been loaded in via our emitter.  We have experimented with changing the size of the sensor film, and this does scale with the number of photons, so we wondered whether the differentiable renderer is doing something clever based on knowing which ray paths cross the sensor and where, or whether there's some form of MonteCarlo method going on which makes what we have implemented an excellent candidate for some embarrassingly parallel method used (probably in DrJit).

There is more detail in this draft paper: https://arxiv.org/pdf/2309.12496 where we are in particular trying to understand results such as those in figures 7 and 8.  (Similar if not identical experiments to this are also on the code fork as detailed earlier).  It might be that this issue/question is better asked on the DrJit repository but I thought I would start here first.

**Comment by ziyi-zhang** [comment]
> We have experimented with changing the size of the sensor film, and this does scale with the number of photons

This is unexpected. As Nicolas said, the number of light paths simulated is simply `#pixels * spp`. Changing the film size should not have any noticeable effect.

**Comment by andrewgait** [comment]
> > We have experimented with changing the size of the sensor film, and this does scale with the number of photons
> 
> This is unexpected. As Nicolas said, the number of light paths simulated is simply `#pixels * spp`. Changing the film size should not have any noticeable effect.

Oops, I mis-spoke there - the problem does scale with the size of the sensor film, not with the number of photons.  I think this is what I would expect based on what Nicolas has said - or am I misunderstanding what you mean by #pixels?  What does it mean if not the number of pixels on the sensor film?

**Comment by njroussel** [comment]
He might have thought that you meant the physical film size ? I'm not too sure. 

@andrewgait I think we addressed the main question, I'll close this issue. We can re-open it if you find other unexpected performance issues related to this `photon` class - just comment on this thread 👍

**Comment by andrewgait** [comment]
Thanks @njroussel and others for the discussion, I'm sure I'll be back at some point with more questions but I'm happy to open new issues for them as appropriate.

**Comment by andrewgait** [comment]
Hi @njroussel - we still have some confusion as to how the sampling method is actually working in our emitter. Obviously it is working in some way because we are seeing expected results! 

We have a single emitter, but multiple photons defined within it in terms of their origin and target coordinates. I presume the integrator/render's random method within `sample(...)` you mention earlier ends up calling `sample_direction(...)` and `sample_ray(...)` within the emitter itself, and from the way our code has been written, this somehow ends up choosing a photon from our (possibly quite large) list of photons that is incident at the sample point, i.e. `sample_direction(...)` is able to work this out based on the coordinate matrix / transform, and then `sample_ray(...)` simply works based upon this and the wavelength sample value?

**Comment by njroussel** [comment]
Yes, exactly!

**Comment by andrewgait** [comment]
@njroussel So this means that not all the photons in our list wil neccessarily be sampled, particularly if we have more photons than there are pixels in the sensor, and the sample count is set to 1?

**Comment by njroussel** [comment]
That's correct.

**Comment by andrewgait** [comment]
> Assuming that the only emitter you have in your scene is a single `photon` instance (which actually defines N real photons), then I think you're set as long as spp > N.
> 
> In the source code for `PhotonEmitter::sample_ray`, the method completely disregards the random sample it is given from the sample, and just equally spaces out the samples per photon ([relevant section](https://github.com/UoMResearchIT/mitsuba3-manchester/blob/dev/src/emitters/photon.cpp#L201-L210)).

Oh - I think I understand.  So what happens in `PhotonEmitter::sample_direction` (which does use the random sample?) is not in fact relevant in any way because it is then disregarded in `PhotonEmitter::sample_ray`?

**Comment by njroussel** [comment]
Indeed! It's not relevant.
